[spotify]
to-listen-playlist = "spotify:playlist:3i2ruN3gPygSsQzcvQG9ri"
test-playlist = "spotify:playlist:4RZVqEcYVkzgExsDRnmwNp"
followed-labels-playlist = "spotify:playlist:4PT220EaTKVNwmkaKqAh4y"
scopes = [
    "playlist-modify-private",
    "playlist-read-private",
    "user-library-read",
]
