name: Test OIDC AWS Access

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test-oidc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: eu-west-1

      - name: Verify AWS caller identity
        run: aws sts get-caller-identity
      
      - name: List objects in test bucket
        run: aws s3 ls s3://radswn-spotify-auth-cache
